apiVersion: apps/v1
kind: Deployment
metadata:
  name: agilecie3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agilecie3-app
  template:
    metadata:
      labels:
        app: agilecie3-app
    spec:
      containers:
      - name: agilecie3-app
        image: anusree0418/agilecie3-app:latest
        ports:
        - containerPort: 5000
