apiVersion: v1
kind: Service
metadata:
  name: agilecie3-frontend-service
spec:
  type: NodePort
  selector:
    app: agilecie3-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
