name: Jupyter Notebook CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install notebook nbconvert

    - name: Execute Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute "Agile SEE-2.ipynb" --output executed.ipynb
